### Requisação para a raiz da aplicação
GET http://localhost:5071

### Listar users
GET http://localhost:5071/user

### Buscar user
GET http://localhost:5071/user/af1006d7-3b56-4510-94ef-0df9f8b39e27	

### Cadastrar user
POST http://localhost:5071/user
Content-Type: application/json

{
    "Name" : "Oswaldo Deco",
    "Email" : "oswaldo96@live.com",
    "Cellphone" : 999999999,
    "taxNumber" : "999999999",
    "Password" : "999999999"
}

### Deletar user
DELETE http://localhost:5071/user/b69da8ff-1f7f-461c-98c6-5ea6dcf73e6c

### Alterar user
PUT http://localhost:5071/user/b69da8ff-1f7f-461c-98c6-5ea6dcf73e6c
Content-Type: application/json

{
    "Name" : "Oswaldo Deco Costa",
    "Email" : "oswaldo100@live.com",
    "Cellphone" : 888888888,
    "taxNumber" : "888888888",
    "Password" : "888888888"
}

###Buscar Payment
GET http://localhost:5071/payment/

###Cadastrat Payment
POST http://localhost:5071/payment/
Content-Type: application/json

{
    "valor": 150,
    "status": "Pendente",
    "Date": "2024-10-20T10:00:00"
}

###Deletar payment
DELETE http://localhost:5071/payment/9da60345-55df-43d6-b0c9-82319aaac5c0

###Altera Payment
PUT http://localhost:5071/payment/9da60345-55df-43d6-b0c9-82319aaac5c0
Content-Type: application/json

{
    "valor": 200,
    "status": "Pago",
    "Date": "2024-10-21T10:00:00"
}

###Listar Spaces
GET http://localhost:5071/spaces

###Buscar Space 
GET http://localhost:5071/spaces/


###Cadastrar Space
POST http://localhost:5071/spaces
Content-Type: application/json

{
    "Name": "Espaço A",
    "Capacity": 50,
    "PricePerHour": 150
}

###Deletar space
DELETE http://localhost:5071/spaces/38f49513-9680-476f-9008-78eef29e71fa

###Alterar Space
PUT http://localhost:5071/spaces/38f49513-9680-476f-9008-78eef29e71fa
Content-Type: application/json

{
    "Name": "Espaço A Modificado",
    "Capacity": 99,
    "PricePerHour": 200
}

###Buscar Booking 
GET http://localhost:5071/bookings


###cadastrar booking
POST http://localhost:5071/bookings
Content-Type: application/json

{
    "Users": "Espaço A"
}

###deletar booking
DELETE http://localhost:5071/bookings/11faa79d-4874-401f-8b99-ac5fca8107fd

###alterar booking
PUT http://localhost:5071/bookings/a31b42e5-d19d-4164-97c4-3722981e7baa
Content-Type: application/json

{
    "users": "Espaço A Modificado"
}