### Requisação para a raiz da aplicação
GET http://localhost:5071

### Listar users
GET http://localhost:5071/user

### Buscar user
GET http://localhost:5071/user/741a6a56-ce34-46d8-964c-02d0baae5155

### Cadastrar user
POST http://localhost:5071/user
Content-Type: application/json

{
    "Name" : "Oswaldo Deco",
    "Email" : "oswaldo96@live.com",
    "Cellphone" : 999999999,
    "taxNumber" : "999999999",
    "Password" : "999999999"
}

### Deletar user
DELETE http://localhost:5071/user/741a6a56-ce34-46d8-964c-02d0baae5155

### Alterar user
PUT http://localhost:5071/user/741a6a56-ce34-46d8-964c-02d0baae5155
Content-Type: application/json

{
    "Name" : "Oswaldo Deco Costa",
    "Email" : "oswaldo100@live.com",
    "Cellphone" : 888888888,
    "taxNumber" : "888888888",
    "Password" : "888888888"
}